# --- STAGE 1: Build ---
FROM node:20-slim as build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build -- --configuration production

# --- STAGE 2: Serve ---
FROM nginx:alpine

COPY --from=build /app/dist/coffee-shop-ui/browser /usr/share/nginx/html

EXPOSE 80