services:
  # --- INFRASTRUCTURE ---
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true

  # --- BACKEND SERVICES ---
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - db-user
    environment:
      - EUREKA_URI=http://eureka-server:8761/eureka/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_DATA_MONGODB_URI=mongodb://db-user:27017/user-db

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - db-product
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_DATA_MONGODB_URI=mongodb://db-product:27017/productdb

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - db-order
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_DATA_MONGODB_URI=mongodb://db-order:27017/orderdb

  # --- FRONTEND ---
  coffee-shop-ui:
    build: ./coffee-shop-ui
    container_name: coffee-shop-ui
    ports:
      - "4200:80"

  # --- DATABASES ---
  db-user:
    image: mongo:latest
    container_name: db-user
    ports:
      - "27020:27017"
    volumes:
      - mongo-user-data:/data/db

  db-product:
    image: mongo:latest
    container_name: db-product
    ports:
      - "27018:27017"
    volumes:
      - mongo-product-data:/data/db

  db-order:
    image: mongo:latest
    container_name: db-order
    ports:
      - "27019:27017"
    volumes:
      - mongo-order-data:/data/db

# Defines the volumes to persist data
volumes:
  mongo-user-data:
  mongo-product-data:
  mongo-order-data:
