services:
  # --- INFRASTRUCTURE ---
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka

  # --- BACKEND SERVICES ---
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3000:3000"
    depends_on:
      - db-user
    environment:
      - MONGO_URI=mongodb://db-user:27017/userdb

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - db-product
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATA_MONGODB_URI=mongodb://db-product:27017/productdb

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - db-order
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATA_MONGODB_URI=mongodb://db-order:27017/orderdb

  # --- FRONTEND ---
  coffee-shop-ui:
    build: ./coffee-shop-ui
    container_name: coffee-shop-ui
    ports:
      - "4200:80"

  # --- DATABASES ---
  # These ports are configured so you can connect locally using Compass
  # or run your services locally using mvn spring-boot:run

  db-user:
    image: mongo:latest
    container_name: db-user
    ports:
      - "27017:27017" # Connect locally via localhost:27017
    volumes:
      - mongo-user-data:/data/db

  db-product:
    image: mongo:latest
    container_name: db-product
    ports:
      - "27018:27017" # Connect locally via localhost:27018
    volumes:
      - mongo-product-data:/data/db

  db-order:
    image: mongo:latest
    container_name: db-order
    ports:
      - "27019:27017" # Connect locally via localhost:27019
    volumes:
      - mongo-order-data:/data/db

# Defines the volumes to persist data
volumes:
  mongo-user-data:
  mongo-product-data:
  mongo-order-data:
