spring.application.name=api-gateway
server.port=8080

# 1. Product Service (Port 8081)
spring.cloud.gateway.server.webflux.routes[0].id=product-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/products/**

# 2. Order Service (Port 8082)
spring.cloud.gateway.server.webflux.routes[1].id=order-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/order/**

# 3. User Service (Port 8084)
spring.cloud.gateway.server.webflux.routes[2].id=user-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8084
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/user/**

# --- CORS (New Format) ---
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-origins=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-headers=*

# Disable Eureka for now
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false