# --- STAGE 1: Build ---
FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn package -DskipTests

# --- STAGE 2: Run ---
# Use the official Java 21 runtime
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app

# This copies the .jar from STAGE 1
COPY --from=build /app/target/product-service.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]