# Use an official Java runtime as a parent image
FROM openjdk:17-jdk-slim

# Set the working directory
WORKDIR /app

# Copy the built .jar file into the container
# (This assumes you build your jar in a 'target' folder)
COPY target/product-service.jar app.jar

# Make port 8080 available
EXPOSE 8080

# Run the jar file
ENTRYPOINT ["java", "-jar", "app.jar"]