# --- STAGE 1: Build ---
FROM maven:3.8-openjdk-17 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn package -DskipTests

# --- STAGE 2: Run ---
FROM openjdk:17-jdk-slim
WORKDIR /app

# This copies the .jar from STAGE 1
COPY --from=build /app/target/order-service.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]