spring.application.name=user-service
server.port=8084
spring.data.mongodb.uri=mongodb://localhost:27020/user-service

eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
