# Use OpenJDK 21 as the base image
FROM openjdk:21-jdk

# Copy the jar file (generated after 'mvn clean package')
COPY target/*.jar app.jar

# Expose the port
EXPOSE 8084

# Run the application
ENTRYPOINT ["java", "-jar", "/app.jar"]